### ISSUE TITLE
0xHati - All proxy upgrades are left uninitialized when upgrading

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ecoprotocol-judging#112]
0xHati

high

# All proxy upgrades are left uninitialized when upgrading

## Summary
Both the L1 and L2 bridge can be upgraded, both contracts have initializers which replace the constructor function in proxy implementations. The upgrade just sets the new implementation, but doesn't initialize it. 
## Vulnerability Detail
An attacker can call `initialize` when the new implementation is deployed. If we look at the following snippet from the L2 bridge and the current `initialize` function, he would be able to set everything and make himself admin and subsequently take over the bridge. Of course we don't have any idea how the new implementation will look like, but nevertheless this is an attack vector that is currently possible. The vulnerability exists in all the proxy contracts at the moment, increasing the likelihood this will happen. 

The current initialize function of the L1 contract. [Link to code](https://github.com/sherlock-audit/2023-05-ecoprotocol/blob/main/op-eco/contracts/bridge/L1ECOBridge.sol#L113)
```solidity
 function initialize(
        address _l1messenger,
        address _l2TokenBridge,
        address _l1Eco,
        address _l2Eco,
        address _l1ProxyAdmin,
        address _upgrader
    ) public initializer {
        CrossDomainEnabledUpgradeable.__CrossDomainEnabledUpgradeable_init(_l1messenger);
        l2TokenBridge = _l2TokenBridge;
        l1Eco = _l1Eco;
        l2Eco = _l2Eco;
        l1ProxyAdmin = ProxyAdmin(_l1ProxyAdmin);
        upgrader = _upgrader;
        inflationMultiplier = IECO(_l1Eco).getPastLinearInflation(block.number);
    }
 ```
## Impact
An attacker can front run `initialize` on the new implementation contract and take over the contract.

## Code Snippet
[Link to code](https://github.com/sherlock-audit/2023-05-ecoprotocol/blob/main/op-eco/contracts/bridge/L1ECOBridge.sol#L174)

For example the `upgradeSelf` function from the `L1ECOBridge`, the `upgrader` calls it to set a new implementation. Below we'll see that OpenZepplin calls `upgradeTo` but the implementation is never initialized.
```solidity
  function upgradeSelf(address _newBridgeImpl) external virtual onlyUpgrader {
        //cast to a payable address since l2EcoToken is the proxy address of a ITransparentUpgradeableProxy contract
        address payable proxyAddr = payable(address(this));

        ITransparentUpgradeableProxy proxy = ITransparentUpgradeableProxy(
            proxyAddr
        );
        l1ProxyAdmin.upgrade(proxy, _newBridgeImpl);

        emit UpgradeSelf(_newBridgeImpl);
    }

```
Upgrade function in `ProxyAdmin.sol`, part of OpenZeppelin. 
```solidity
  function upgrade(ITransparentUpgradeableProxy proxy, address implementation) public virtual onlyOwner {
        proxy.upgradeTo(implementation);
    }
```
## Tool used

Manual Review

## Recommendation
There are different options, the simplest one would be to use [`upgradeToAndCall`](https://docs.openzeppelin.com/contracts/4.x/api/proxy#ProxyAdmin-upgradeAndCall-contract-ITransparentUpgradeableProxy-address-bytes-), which immediately calls a function within the new contract, making everything an atomic transaction. Another option is protecting the `initialize` function, this protects anyone from calling the `initialize` function, though it still can leave the contract in an uninitialized state. 
Also UUPS might be a good solution since it also guarantees that the new implementation can be upgraded. But this is a radical change and can introduce other vulnerabilities. I recommend the project use `upgradeToAndCall` instead of `upgrade` in all occurrences.

**Comment by boulderbytes** [comment]
Escalate for 10 USDC

I would like to hear the judges perspective as to why this was excluded. Reading the docs I understand this how Sherlock views initializers:
 
>Front-running initializers: Front-running initializers where there is no irreversible damage or loss of funds & the protocol could just redeploy and initialize again is not a valid issue.

Here we are not talking about an initial deploy where we can redeploy, we are talking about a live upgrade of either the L1 or L2 bridge.
Front running the `initialize` call of the new upgrade means taking over the bridge.

1. L1EcoBridge.upgradeL2Bridge is called
2. L2EcoBridge.upgradeSelf is invoked
3. Proxy sets new implementation address
4. Another transaction is needed to call `initialize` on the new implementation, this can be front run.

The same applies for the upgrade of the L1EcoBridge and the Eco token.

`upgradeToAndCall` should be used so the new upgrade can be initialized immediately in one transaction to avoid any issues such as front running.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> I would like to hear the judges perspective as to why this was excluded. Reading the docs I understand this how Sherlock views initializers:
>  
> >Front-running initializers: Front-running initializers where there is no irreversible damage or loss of funds & the protocol could just redeploy and initialize again is not a valid issue.
> 
> Here we are not talking about an initial deploy where we can redeploy, we are talking about a live upgrade of either the L1 or L2 bridge.
> Front running the `initialize` call of the new upgrade means taking over the bridge.
> 
> 1. L1EcoBridge.upgradeL2Bridge is called
> 2. L2EcoBridge.upgradeSelf is invoked
> 3. Proxy sets new implementation address
> 4. Another transaction is needed to call `initialize` on the new implementation, this can be front run.
> 
> The same applies for the upgrade of the L1EcoBridge and the Eco token.
> 
> `upgradeToAndCall` should be used so the new upgrade can be initialized immediately in one transaction to avoid any issues such as front running.
> 
> 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by albertnbrown** [comment]
https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/core/contracts/Initializable.sol#L37

If you see here on Initializable.sol (which all contracts inherit from), functions marked with the `initializer()` modifier cannot be called so long as `initialized` is set to true, which is done during the deploy of the proxy. That means that all `initializer()` functions are disabled for the lifetime of the proxy, even if they are separate contracts bound later through upgrades.

**Comment by boulderbytes** [comment]
For new upgrades you can use `reinitializer` in case new variables need to be set or updated.
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/4fd2f8be339e850c32206342c3f9a1a7bedbb204/contracts/proxy/utils/Initializable.sol#L119

If a `reinitializer` is used to set new variables this can be frontrun. Since in the upgrade it's only calling `upgradeTo` and not `upgradeToAndCall`, note even with the latter, the data or function to be called is optional. 

Example for `reinitializer`:
```solidity
contract MyToken is ERC20Upgradeable {
    function initialize() initializer public {
        __ERC20_init("MyToken", "MTK");
    }
}

contract MyTokenV2 is MyToken, ERC20PermitUpgradeable {
    function initializeV2() reinitializer(2) public {
        __ERC20Permit_init("MyToken");
    }
}
```

**Comment by albertnbrown** [comment]
Yes, but we don't want to, that's why there's no protection on the function. This was just referring to your specific escalation.

**Comment by boulderbytes** [comment]
Ok, this can be closed, thanks to the sponsor for taking the time to respond.

**Comment by hrishibhat** [comment]
Escalation rejected

Invalid issue
Maintaining the state of the issue as is based on the above comments.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Invalid issue
> Maintaining the state of the issue as is based on the above comments.

    This issue's escalations have been rejected!

    Watsons who escalated this issue will have their escalation amount deducted from their next payout.
