### ISSUE TITLE
0xdeadbeef - Protocol instructions can lead to loss of funds

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ecoprotocol-judging#113]
0xdeadbeef

high

# Protocol instructions can lead to loss of funds

## Summary

Withdrawing from L2 requires the user to set the l1gas limit.
According to the code documentation and discord chat the l1gas limit is not used and should not be worried about:
`_l1Gas (on the L2ECOBridge) has been noted by this comment in their docs: @param _l1Gas Unused, but included for potential forward compatibility considerations. We keep the parameter for the same reason as above but it should not be worried about`

While this was true pre-bedrock. Post-bedrock this parameter is important and enforced. 

## Vulnerability Detail

As can be seen in the below comment and in the discord channel the _l1Gas (on the L2ECOBridge) is noted to be unused and not to worry about.
https://github.com/sherlock-audit/2023-05-ecoprotocol/blob/main/op-eco/contracts/bridge/L2ECOBridge.sol#L226

Therefore, users can expect that any value there is acceptable. Even values that are above the actual required gas or above the L1 block gas limit.

If the l1gas will be set for example as `type(uint32).max` the tokens on L2 will be burned and a message will be sent to L1.

in L1 OptimismPortal, where transaction are validated and executed there is a check to see if enough gas has been supplied to execute the transaction. 
https://github.com/ethereum-optimism/optimism/blob/aef727647d293b91e73e4248cae0c297ac492733/packages/contracts-bedrock/contracts/libraries/SafeCall.sol#L119-L124
https://github.com/ethereum-optimism/optimism/blob/aef727647d293b91e73e4248cae0c297ac492733/packages/contracts-bedrock/contracts/libraries/SafeCall.sol#L91

```solidity
        bool _hasMinGas = hasMinGas(_minGas, 0);
        assembly {
            // Assertion: gasleft() >= (_minGas * 64) / 63 + 40_000
            if iszero(_hasMinGas) {
                // Store the "Error(string)" selector in scratch space.
                mstore(0, 0x08c379a0)
```

```solidity
    function hasMinGas(uint256 _minGas, uint256 _reservedGas) internal view returns (bool) {
        bool _hasMinGas;
        assembly {
            // Equation: gas × 63 ≥ minGas × 64 + 63(40_000 + reservedGas)
            _hasMinGas := iszero(
                lt(mul(gas(), 63), add(mul(_minGas, 64), mul(add(40000, _reservedGas), 63)))
            )
        }
        return _hasMinGas;
    }
```

If `type(uint32).max` (or any number close to the block gas limit) is passed as the gas limit the transaction will revert and tokens will be permanently lost.

It is important to emphasize that this is not a USER error. The protocol has actively mentioned that the `l1Gas` will not be used and has not recommended what value it should have.

## Impact

Loss of funds

## Tool used

Manual Review

## Recommendation

1. Limit the value of `l1gas` to a number much smaller then the block gas limit (suggesting 1M).
2. Add a warning in the comments and description

**Comment by 0xdeadbeef0x** [comment]
Escalate for 10 USDC

Appreciate the sponsors response and fix.
This should be rewarded because of the following points:
1. The comments were cloned by pre-bedrock bridge and not post-bedrock. Post-bedrock indeed mentions the correct comment (minimum gas limit): https://github.com/ethereum-optimism/optimism/blob/0638daf505ee5fe0ccda418b4f85a7611a9fdd8d/packages/contracts-bedrock/contracts/universal/StandardBridge.sol#L226
2. As common in previous Sherlock contest judging, a dispute that an issue is a none-issue because of UI enforcement is not sufficient. Anyone can use the smart contracts directly without using the sponsors UI.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> Appreciate the sponsors response and fix.
> This should be rewarded because of the following points:
> 1. The comments were cloned by pre-bedrock bridge and not post-bedrock. Post-bedrock indeed mentions the correct comment (minimum gas limit): https://github.com/ethereum-optimism/optimism/blob/0638daf505ee5fe0ccda418b4f85a7611a9fdd8d/packages/contracts-bedrock/contracts/universal/StandardBridge.sol#L226
> 2. As common in previous Sherlock contest judging, a dispute that an issue is a none-issue because of UI enforcement is not sufficient. Anyone can use the smart contracts directly without using the sponsors UI.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by albertnbrown** [comment]
The comments come from an external package and not from our codebase. I'm unsure why pointing that out is being used as a justification of why this is relevant.

I understand that people can interact directly with the contract, but in that case I feel like they should be expected to understand optimism to do so. If they did they would know the effect of the gas value. I don't feel like documentation is a functional issue.

**Comment by 0xffff11** [comment]
Agree with sponsor

**Comment by hrishibhat** [comment]
Escalation rejected

Valid low
> The comments come from an external package and not from our codebase. I'm unsure why pointing that out is being used as a justification of why this is relevant.
Documentation error on an integrating protocol code can be considered a valid low. 
Ther is no vulnerability in the code and when interacting with directly it behaves as it should.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Valid low
> > The comments come from an external package and not from our codebase. I'm unsure why pointing that out is being used as a justification of why this is relevant.
> Documentation error on an integrating protocol code can be considered a valid low. 
> Ther is no vulnerability in the code and when interacting with directly it behaves as it should. 

    This issue's escalations have been rejected!

    Watsons who escalated this issue will have their escalation amount deducted from their next payout.
