### ISSUE TITLE
p0wd3r - L2 ECO should be initialized using the parameter setting `linearInflationMultiplier` with the value of `L1Bridge.inflationMultiplier` instead of a fixed value.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ecoprotocol-judging#2]
p0wd3r

medium

# L2 ECO should be initialized using the parameter setting `linearInflationMultiplier` with the value of `L1Bridge.inflationMultiplier` instead of a fixed value.

## Summary
L2 ECO should be initialized using the parameter setting `linearInflationMultiplier` with the value of `L1Bridge.inflationMultiplier` instead of a fixed value.

A fixed value will cause the `linearInflationMultiplier` of L1 and L2 to be inconsistent, resulting in inconsistent conversion rates between cross-chain transactions and conversion rates after rebase.

The amount of tokens received by users who mint before and after the rebase is inconsistent, while the `linearInflationMultiplier` in L1 remains unchanged.
## Vulnerability Detail
L2 ECO set `linearInflationMultiplier` to `constant INITIAL_INFLATION_MULTIPLIER` during initialization, which may differ from the `linearInflationMultiplier` of L1 ECO.
https://github.com/eco-association/op-eco/blob/main/contracts/token/L2ECO.sol#L154
```solidity
linearInflationMultiplier = INITIAL_INFLATION_MULTIPLIER;
```

And the `linearInflationMultiplier` can only be changed through the rebase function, which by default can only be modified through L2 Bridge.
https://github.com/eco-association/op-eco/blob/main/contracts/token/L2ECO.sol#L251-L257
```solidity
    function rebase(uint256 _newLinearInflationMultiplier)
        external
        onlyRebaserRole
    {
        _rebase(_newLinearInflationMultiplier);
        emit NewInflationMultiplier(_newLinearInflationMultiplier);
    }
```

And once the L2 Bridge is deployed, the deposit function of the L2 Bridge is enabled. Since both L1 and L2 use `inflationMultiplier` to calculate token amounts, this may introduce the following scenario:

1. Deploy L2 ECO, initialize setting `linearInflationMultiplier` to `INITIAL_INFLATION_MULTIPLIER`, assuming it is 2 here.
2. Deploy L2 Bridge
3. At this time, the `linearInflationMultiplier` of L1 ECO is not equal to the `INITIAL_INFLATION_MULTIPLIER`, assuming it is 3 here.
4. Alice called the L1 Bridge deposit and deposited 6 L1ECO. The final minted amount on L2 is 6 * 3 / 2 = 9.
5. Someone called `rebase` on L1 Bridge which made `linearInflationMultiplier` same on L1 and L2.
6. Bob called the L1 Bridge deposit and deposited 6 L1ECO. The final minted amount on L2 is 6 * 3 / 3 = 6.
7. Ultimately, with the L1 `linearInflationMultiplier` remaining unchanged, Alice and Bob minted different amounts of L2ECO, resulting in unfairness.
## Impact
This will cause the `linearInflationMultiplier` of L1 and L2 to be inconsistent, resulting in inconsistent conversion rates between cross-chain transactions and conversion rates after rebase.

The amount of tokens received by users who mint before and after the rebase is inconsistent, while the `linearInflationMultiplier` in L1 remains unchanged.
## Code Snippet
https://github.com/eco-association/op-eco/blob/main/contracts/token/L2ECO.sol#L154
https://github.com/eco-association/op-eco/blob/main/contracts/token/L2ECO.sol#L251-L257
## Tool used

Manual Review

## Recommendation
L2 ECO should be initialized using the parameter setting `linearInflationMultiplier` with the value of `L1Bridge.inflationMultiplier` instead of a fixed value.

**Comment by imp0wd3r** [comment]
Escalate for 10 USDC

I think this is a valid medium-risk vulnerability, caused by incorrect protocol settings that result in unfairness among users.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> I think this is a valid medium-risk vulnerability, caused by incorrect protocol settings that result in unfairness among users.

    You've deleted an escalation for this issue.
