### ISSUE TITLE
p0wd3r - There is no function in L2 Bridge to update role in L2ECO

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ecoprotocol-judging#3]
p0wd3r

medium

# There is no function in L2 Bridge to update role in L2ECO

## Summary
There is no function in L2 Bridge to update role in L2ECO, L2ECO cannot execute functions such as `updateMinter`.
## Vulnerability Detail
L2ECO set the L2 Bridge address during initialization, which can set the role in L2ECO. Initially, `updateMinter`, `updateBurners`, `updateRebasers` and `updateTokenRoleAdmin` all require execution by the L2 Bridge.

https://github.com/eco-association/op-eco/blob/main/contracts/token/L2ECO.sol#L146-L160
```solidity
    function initialize(
        address _l1Token,
        address _l2Bridge
    ) public initializer {
        ERC20Upgradeable.__ERC20_init(
            "ECO",
            "ECO"
        );
        linearInflationMultiplier = INITIAL_INFLATION_MULTIPLIER;
        minters[_l2Bridge] = true;
        burners[_l2Bridge] = true;
        rebasers[_l2Bridge] = true;
        l1Token = _l1Token;
        tokenRoleAdmin = _l2Bridge;
    }
```
https://github.com/eco-association/op-eco/blob/main/contracts/token/L2ECO.sol#L208-L222
```solidity
    function updateRebasers(address _key, bool _value)
        public
        onlyTokenRoleAdmin
    {
        rebasers[_key] = _value;
    }

    function updateTokenRoleAdmin(address _newAdmin) public onlyTokenRoleAdmin {
        tokenRoleAdmin = _newAdmin;
    }
```

**But there is no entry point to call these functions in L2 Bridge.**

In the test file, only the address of L2 Bridge was simulated instead of calling the functions in L2 Bridge.
https://github.com/eco-association/op-eco/blob/main/test/L2ECO.spec.ts#L199-L201
```js
        await eco
          .connect(l2BridgeImpersonator)
          .updateMinters(alice.address, true)
```
## Impact
The `updateMinters`, `updateBurners`, `updateRebasers` and `updateTokenRoleAdmin` in L2ECO cannot be executed.
## Code Snippet
https://github.com/eco-association/op-eco/blob/main/contracts/token/L2ECO.sol#L146-L160
https://github.com/eco-association/op-eco/blob/main/contracts/token/L2ECO.sol#L208-L222
https://github.com/eco-association/op-eco/blob/main/test/L2ECO.spec.ts#L199-L201
## Tool used

Manual Review

## Recommendation
Add corresponding functions in L2 Bridge.

**Comment by imp0wd3r** [comment]
Escalate for 10 USDC

I think this is a valid medium-risk vulnerability, which renders the permission management function of the L2ECO protocol meaningless.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> I think this is a valid medium-risk vulnerability, which renders the permission management function of the L2ECO protocol meaningless.

    You've deleted an escalation for this issue.

**Comment by albertnbrown** [comment]
These functions are intentionally not callable. What this code pattern does is make it so that L2ECO does not need to be upgraded in the future if new contracts need to be given these roles. Instead the upgrade would involve the bridge or a delegateCall from the bridge.
