### ISSUE TITLE
Dug - Implementing `IL2StandardERC20` incorrectly signals that the pre-bedrock standard bridge can be used

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ecoprotocol-judging#67]
Dug

high

# Implementing `IL2StandardERC20` incorrectly signals that the pre-bedrock standard bridge can be used

## Summary

Because the `IL2StandardERC20` interface is implemented by `L2ECO`, user deposits into the pre-bedrock standard bridge, which would normally be reversed, will not be handled properly and funds will be lost.

## Vulnerability Detail

`IL2StandardERC20` was used by pre-bedrock Optimism contracts to signal that they were compatible with the standard bridge. There was an ERC165 check for it when deposits we're finalized. See the code below.

https://github.com/ethereum-optimism/optimism/blob/95978376a208e24a3ad03ba816dca89ae95a08dd/packages/contracts/contracts/L2/messaging/L2StandardBridge.sol#L141-L187
```solidity
    null(
        address _l1Token,
        address _l2Token,
        address _from,
        address _to,
        uint256 _amount,
        bytes calldata _data
    ) external virtual onlyFromCrossDomainAccount(l1TokenBridge) {
        // Check the target token is compliant and
        // verify the deposited token on L1 matches the L2 deposited token representation here
        if (
            // slither-disable-next-line reentrancy-events
            ERC165Checker.supportsInterface(_l2Token, 0x1d1d8b63) &&
            _l1Token == IL2StandardERC20(_l2Token).l1Token()
        ) {
            // When a deposit is finalized, we credit the account on L2 with the same amount of
            // tokens.
            // slither-disable-next-line reentrancy-events
            IL2StandardERC20(_l2Token).mint(_to, _amount);
            // slither-disable-next-line reentrancy-events
            emit DepositFinalized(_l1Token, _l2Token, _from, _to, _amount, _data);
        } else {
            // Either the L2 token which is being deposited-into disagrees about the correct address
            // of its L1 token, or does not support the correct interface.
            // This should only happen if there is a  malicious L2 token, or if a user somehow
            // specified the wrong L2 token address to deposit into.
            // In either case, we stop the process here and construct a withdrawal
            // message so that users can get their funds out in some cases.
            // There is no way to prevent malicious token contracts altogether, but this does limit
            // user error and mitigate some forms of malicious contract behavior.
            bytes memory message = abi.encodeWithSelector(
                IL1ERC20Bridge.finalizeERC20Withdrawal.selector,
                _l1Token,
                _l2Token,
                _to, // switched the _to and _from here to bounce back the deposit to the sender
                _from,
                _amount,
                _data
            );

            // Send message up to L1 bridge
            // slither-disable-next-line reentrancy-events
            sendCrossDomainMessage(l1TokenBridge, 0, message);
            // slither-disable-next-line reentrancy-events
            emit DepositFailed(_l1Token, _l2Token, _from, _to, _amount, _data);
        }
    }
```

> Side note, you'll find that the `IL2StandardERC20` interface isn't used at all in Bedrock. Instead, an `IOptimismMintableERC20` interface is used to signal standard bridge compatibility. 

By implementing `IL2StandardERC20`, you signal that the token is compatible with the pre-bedrock standard bridge when actually, they are very incompatible.

An issue is created where users can deposit using the pre-bedrock standard bridge, however, when an attempt is made to finalize the deposit on L2, the transaction will revert as the standard bridge is unable to mint the L2 tokens because it does not have permission.

The fact that the ERC165 check passes, causes their transaction to not be reversed on L1 (the else block is not executed). The bridge would normally reverse the L1 deposit when `IL2StandardERC20` is not supported. 

## Impact

By signaling that L2ECO is supports the `IL2StandardERC20`, you cause the pre-bedrock standard bridge to permanently lock up user deposits.

## Code Snippet

https://github.com/sherlock-audit/2023-05-ecoprotocol/blob/main/op-eco/contracts/token/L2ECO.sol#L264-L274

https://github.com/sherlock-audit/2023-05-ecoprotocol/blob/main/op-eco/contracts/token/L2ECO.sol#L96-L99

https://github.com/sherlock-audit/2023-05-ecoprotocol/blob/main/op-eco/contracts/token/L2ECO.sol#L229-L232

## Tool used

Manual Review

## Recommendation

If you do not support the pre-bedrock standard bridge, you should not implement the `IL2StandardERC20` interface.

```diff
    function supportsInterface(bytes4 _interfaceId) external pure returns (bool) {
-       bytes4 firstSupportedInterface = type(IERC165).interfaceId; // ERC165
-       bytes4 secondSupportedInterface = type(IL2StandardERC20).interfaceId; // compliant to OP's IL2StandardERC20
-       return _interfaceId == firstSupportedInterface || _interfaceId == secondSupportedInterface;
+       return _interfaceId == type(IERC165).interfaceId;
    }
```

By removing `IL2StandardERC20` as a supported interface, user deposits will correctly be returned to them on L1 if they attempt to deposit using the pre-bedrock standard bridge.

**Comment by dugdaniels** [comment]
Escalate for 10 USDC

I would appreciate if this issue could reconsidered as valid because of the following reasons.

- The `IL2StandardERC20` is only used by the pre-bedrock protocol as a way to verify that deposited tokens support the protocol. As the ECO token is only meant to be used on the bedrock standard bridge, it should not implement the `IL2StandardERC20`.  The `IL2StandardERC20` interface is not a part of bedrock at all.
- By implementing the `IL2StandardERC20` interface, the protocol is overriding built-in safeguards on the pre-bedrock bridge that prevent tokens from being deposited if they do not support it. 
- The ECO token does not support the pre-bedrock bridge and will be lost if deposited into it. Normally, this deposit would revert, but since the `IL2StandardERC20` interface is implemented, it will not.
- By implementing the irrelevant `IL2StandardERC20` interface, the developers are introducing an issue that will result in a loss of funds if a user uses the pre-bedrock optimism bridge, a scenario that will be very likely to happen considering how new these protocols are and how uninformed the majority of users are about them.

**Comment by albertnbrown** [comment]
I agree with you here, however, I have received some guidance from OP that they use an ERC165 check for integrations with their interface. While you are right here, I have been told that this mis-signaling is a required feature for integration with app.optimism.io. You can see here: https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/358 we are adding our token contracts with the associated bridges to their token-list which means they will bypass the StandardBridge and instead use our custom bridge.

**Comment by dugdaniels** [comment]
> I have been told that this mis-signaling is a required feature for integration with app.optimism.io.

Ah, weird. Seems like... they shouldn't be doing that. 🙃

I would think this could cause issues if wallets and other services built their own UIs for bridging via the standard bridge.

**Comment by ctf-sec** [comment]
Based on the above comments, can be a valid low

**Comment by hrishibhat** [comment]
Escalation rejected

Valid low
Based on the above comments this seems to intended

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Valid low
> Based on the above comments this seems to intended

    This issue's escalations have been rejected!

    Watsons who escalated this issue will have their escalation amount deducted from their next payout.
