### ISSUE TITLE
shogoki - User might mint Tokens without depositing - Inconsistent assumptions for return value of transfer/transferfrom

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-ecoprotocol-judging#81]
shogoki

medium

# User might mint Tokens without depositing - Inconsistent assumptions for return value of transfer/transferfrom

## Summary

The contract takes some assumptions about calling transfer/transferFrom, as it is intended to always be used with the ECO token.
However, this assumptions are not consistent throughout the code, which enables us to assume, that the behaviour might change in future and a check for the return value of `transfer`/`transferFrom` is necessary to ensure a succesful transfer.

## Vulnerability Detail

There are multiple places where `transfer`/`transferFrom` is called in the contracts. Sometimes the contract checks for the return value, sometimes not.
in `_initiateERC20Deposit` in L1ECOBridge `transferFrom` is called without checking for any return value. It is assumed, that the transfer was successfull if it did not revert.
However in the same contract in `finalizeERC20Withdrawal` there is an encoded call to `transfer`, and afterwards there is a check if the Transaction reverted **AND** did return `true`. 
Right now the ECO token should always revert on failed transfers, but as it is an upgradable Token, this might change in future. The Token does indeed return true on successful transfers. 
As there is a check for the return value in another function we are to assume that this might be/become a necessary check to do. Therefore we can assume, that there is a possibility for the unchecked `transferFrom` in `_initiateERC20Deposit` top silently fail.
If this is the case, an attacker could force it to silently fail and be able to mint Tokens on L2 without actually depositing on L1, as the `_initiateERC20Deposit` goes on to send a Corsschainmessage and call `finalizeDeposit` on L2ECOBridge which is going to mint tokens to our address.

## Impact

If the first Token transfer would silently fail, because there was a missing check for the return, a user might gain Tokens on. L2, without depositing on L1.

## Code Snippet

Unchecked return value:

https://github.com/sherlock-audit/2023-05-ecoprotocol/blob/main/op-eco/contracts/bridge/L1ECOBridge.sol#L333

Checked return value:

https://github.com/sherlock-audit/2023-05-ecoprotocol/blob/main/op-eco/contracts/bridge/L1ECOBridge.sol#L247-L257

Call to L2 Contract:

https://github.com/sherlock-audit/2023-05-ecoprotocol/blob/main/op-eco/contracts/bridge/L1ECOBridge.sol#L335-L347

L2 contract is going to mint tokens:

https://github.com/sherlock-audit/2023-05-ecoprotocol/blob/main/op-eco/contracts/bridge/L2ECOBridge.sol#L161-L162

## Tool used

Manual Review

## Recommendation

Check for return value of `transferFrom` in `_initiateERC20Deposit` of L1ECOBridge.

**Comment by Shogoki** [comment]
Escalate for 10 USDC

I think this issue should be reconsidered to be valid:

I guess it was rejected because the only Token that is intended to use is the ECO Token, and it’s current implementation reverts on failures.
But, as stated in the report:

1. The Token Contract is upgradable, which means behaviour can be changed!
2. The Developers themselves seem to believe the return value should be checked! Because they do this exact thing in another function of the contract.
3. If the behaviour is changed, the missing check has an significant impact for the protocol.

I think especially number 2 weighs into considering this issue valid. While 1 states the technical possibility and 3 the possible impact.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> I think this issue should be reconsidered to be valid:
> 
> I guess it was rejected because the only Token that is intended to use is the ECO Token, and it’s current implementation reverts on failures.
> But, as stated in the report:
> 
> 1. The Token Contract is upgradable, which means behaviour can be changed!
> 2. The Developers themselves seem to believe the return value should be checked! Because they do this exact thing in another function of the contract.
> 3. If the behaviour is changed, the missing check has an significant impact for the protocol.
> 
> I think especially number 2 weighs into considering this issue valid. While 1 states the technical possibility and 3 the possible impact.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JeffCX** [comment]
Don't think the severity is high enough to be a medium, can be a valid low.

**Comment by hrishibhat** [comment]
Escalation rejected

Valid low
There is no medium/high impact described here. The assumptions are based on the upgrade of a token.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Valid low
> There is no medium/high impact described here. The assumptions are based on the upgrade of a token. 
> 

    This issue's escalations have been rejected!

    Watsons who escalated this issue will have their escalation amount deducted from their next payout.

**Comment by albertnbrown** [comment]
I agree that there is no impact. It is best practices, thought, so we might fix but just because it'll be prettier if we do it nicely.
